JWT
sp-team-lutsk/cyber_security_web_portal pull request #1
Opened 2019-06-25 14:04 UTC by Martinfree

Зробив своє завдання. Скріншот роботи JWT(моделі та форми юзера не створював, тому мусив перевіряти його роботу так):
![Снимок экрана от 2019-06-25 14-18-18](https://user-images.githubusercontent.com/51124748/60104810-7b232200-9762-11e9-8744-68e1c39c7f46.png)

Allauth добавив в settings.py і вказав в провайдерах тільки Google та Facebook (думаю, цього вистачить)

2019-06-25 14:37 UTC, m-pasha commented
Добав будь ласка файл requirements.txt де буде список пакетів і їх версій використані в проекті. Коли я скачую проект `git clone repo/repo.git` то в енві запускаєш `pip install -r requirements.txt` і відразу інсталює тобі все потрібні для проекту версії пакетів. https://pip.pypa.io/en/stable/user_guide/

2019-06-26 18:26 UTC, pavlo-mk requested changes
Please add **requirements file** like this 
`certifi==2018.8.24
chardet==3.0.4
defusedxml==0.5.0
Django==2.1.2
django-allauth==0.38.0
djangorestframework==3.8.2
idna==2.7`

2019-06-26 18:56 UTC, Martinfree commented
ну, типу зробив

2019-06-26 18:57 UTC, m-pasha commented on requiments.md
> +Django==2.1
Розширення має бути зазвичай `.txt `  або `.pip`   >>  `requirements.txt`,  `base.pip`,  `dev.txt`  приклад

2019-06-26 19:16 UTC, m-pasha commented on requiments.md
> +Django==2.1
бажано не використовувати  вкладених папок з однаковими назвами `LNTU_SITE/LNTU_SITE/`   і не називати ВЕЛИКИМИТ 
 БУКВАМИ, а зазвичай малими

2019-06-27 18:37 UTC, merged