Static
sp-team-lutsk/cyber_security_web_portal pull request #16
Opened 2019-08-12 19:14 UTC by romaoksenyuk

2019-08-13 16:44 UTC, pavlo-mk requested changes
Please remove from PR all files `api/static/`

2019-08-13 16:44 UTC, m-pasha commented on api/settings/base.py
> +STATIC_ROOT = "/opt/docker_polls_group/api/static/"
please use `BASE_DIR, static`
BASE_DIR = /opt/docker_polls_group/api/
BASE_DIR is folder where we have manage.py.

2019-08-13 16:52 UTC, m-pasha commented on api/settings/base.py
> +STATIC_ROOT = "/opt/docker_polls_group/api/static/"
@romaoksenyuk 
STATIC_URL = url for found some static files
STATIC_ROOT = all files will be copied when you make on server `collectstatic` command (in Prod)
STATICFILES_DIRS = if you run `collectstatic` command django found files from paths and copy to STATIC_ROOT folder (in Prod)
[DOCS](https://docs.djangoproject.com/en/2.2/howto/static-files/).

2019-08-13 16:53 UTC, m-pasha commented
@romaoksenyuk 
STATIC_URL = url for found some static files
STATIC_ROOT = all files will be copied when you make on server `collectstatic` command (in Prod)
STATICFILES_DIRS = if you run `collectstatic` command django found files from paths and copy to STATIC_ROOT folder (in Prod)
[DOCS](https://docs.djangoproject.com/en/2.2/howto/static-files/).

2019-08-14 19:08 UTC, pavlo-mk requested changes

2019-08-14 19:08 UTC, m-pasha commented on api/settings/base.py
> +sys.path.append(os.path.join(BASE_DIR, 'static'))
Where you will use this path?

2019-08-14 19:08 UTC, m-pasha commented on api/settings/base.py
> +    os.path.join(BASE_DIR, 'static'),
Its wrong practice use `os.path.join` in this settings. Please check docs and use simple path `STATIC_ROOT = /allstatic/` If folder put in BASE_DIR you can use simple path without `os.path.join`.

2019-08-15 19:01 UTC, pavlo-mk approved these changes
Please make merge.

2019-08-15 19:02 UTC, m-pasha commented
@klekhaav please approve if correct for you.

2019-08-15 19:47 UTC, klekhaav approved these changes

2019-08-15 19:48 UTC, merged