Postgresql
sp-team-lutsk/cyber_security_web_portal pull request #21
Opened 2019-08-16 18:26 UTC by Martinfree

2019-08-16 19:35 UTC, m-pasha commented
@Martinfree please add header to PR

2019-08-17 11:59 UTC, pavlo-mk requested changes
Please add description and trello card if it is. Thanks.

2019-08-17 14:20 UTC, klekhaav commented on api/authentication/models.py
> +    username = None
Check username field definition.

2019-08-17 14:21 UTC, klekhaav commented
Looks fine, add link to trello, and add description as Pasha shared in slack

2019-08-18 18:36 UTC, pavlo-mk approved these changes

2019-08-18 18:37 UTC, merged