Api endpoints
sp-team-lutsk/cyber_security_web_portal pull request #31
Opened 2019-09-10 12:46 UTC by Martinfree

2019-09-10 16:38 UTC, m-pasha commented on api/authentication/models.py
> +from settings import base
dont use this import in future its bad practice
please use example in [docs](https://docs.djangoproject.com/en/2.2/topics/settings/#using-settings-in-python-code) `from django.conf import settings`

2019-09-10 17:27 UTC, pavlo-mk requested changes
Added small comments for changes please let me know if you have a question.

2019-09-10 17:27 UTC, pavlo-mk commented on api/authentication/models.py
> +                    'settings': base,
why you need this option `settings` in context template ??

2019-09-10 17:27 UTC, pavlo-mk commented on api/authentication/models.py
>          return short_name.strip()
you can make simple code here like `return self.first_name.strip()` without variable

2019-09-10 17:27 UTC, pavlo-mk commented on api/authentication/models.py
> +        if code:
what will be if no code in args? please update logic for this method

2019-09-10 17:27 UTC, pavlo-mk commented on api/authentication/models.py
> +            except (BadSignature, StdUser.DoesNotExist, TypeError, UnicodeDecodeError) as e:
second `except` not need at this place, please check the logic

2019-09-10 17:27 UTC, pavlo-mk commented on api/authentication/models.py
> +                'settings': base,
the same question with `base` var, where you will use it?

2019-09-10 17:27 UTC, pavlo-mk commented on api/authentication/serializers.py
> +        if validate_password(password=validated_data.get('password',), user=validated_data.get('email'), password_validators=None) is not None:
small changes: many chars in one line, please use in your practice 120 per line

2019-09-10 17:27 UTC, pavlo-mk commented on api/authentication/serializers.py
> +         user = User.objects.get(email=email).first()
`get()` method return only one object

2019-09-10 17:27 UTC, m-pasha commented on api/authentication/views.py
> +import settings
the same dont use `import settings` its bad practice

2019-09-11 19:47 UTC, m-pasha commented
@Martinfree please add description for PR, trello card link, description changes, new features.

2019-09-11 20:19 UTC, Martinfree commented on api/authentication/models.py
> +                    'settings': base,
Because in html template i need url for redirect link, which in base.py

2019-09-11 20:24 UTC, Martinfree commented
Trelli cards:
1. https://trello.com/c/LTYCqnrX/67-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D0%B8-%D0%B0%D0%BF%D1%96-%D0%B5%D0%BD%D0%B4%D0%BF%D0%BE%D0%B9%D0%BD%D1%82%D0%B8-%D0%B4%D0%BB%D1%8F-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D1%96%D1%97
2. https://trello.com/c/0tzTdWKC/66-%D0%BE%D0%B1%CA%BC%D1%94%D0%B4%D0%BD%D0%B0%D1%82%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D1%96%D1%8E-allauth-jwt-%D1%82%D0%B0-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C-%D0%BF%D0%BE%D1%82%D0%BE%D1%87%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D1%82%D1%83%D0%B2%D0%B0%D1%87%D0%B0 (allauth problems)

2019-09-11 20:29 UTC, m-pasha commented on api/authentication/models.py
> +                    'settings': base,
You don't need export all settings file into html, its  not secure. You would add only one variable please use `settings.LOGIN_REDIRECT_URL`

2019-09-11 20:29 UTC, Martinfree commented on api/authentication/models.py
> +        if code:
If we don't have any code - you not to be here, that function calling once with create user

2019-09-11 20:32 UTC, m-pasha commented
^^ please add this links in to main description of this PR. Edit from above please))

2019-09-11 20:34 UTC, Martinfree commented on api/authentication/models.py
> +                    'settings': base,
How i verify user in LOGIN_REDIRECT_URL?

2019-09-11 20:36 UTC, m-pasha commented on api/authentication/models.py
> +        if code:
What happens when this if statement fails?

2019-09-11 20:40 UTC, m-pasha commented on api/authentication/models.py
> +                    'settings': base,
its only example about. You can't import all settings in context, If you have any secrets in settings, What happens? Is it secure?

2019-09-11 20:50 UTC, Martinfree commented on api/authentication/models.py
> +                    'settings': base,
Ok, i'll take it. Thanks for the advice, soon i'll change it

2019-09-18 19:16 UTC, closed without merging