Api endpoints
sp-team-lutsk/cyber_security_web_portal pull request #32
Opened 2019-09-15 18:29 UTC by Martinfree

1. https://trello.com/c/0tzTdWKC/66-%D0%BE%D0%B1%CA%BC%D1%94%D0%B4%D0%BD%D0%B0%D1%82%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D1%96%D1%8E-allauth-jwt-%D1%82%D0%B0-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C-%D0%BF%D0%BE%D1%82%D0%BE%D1%87%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D1%82%D1%83%D0%B2%D0%B0%D1%87%D0%B0
2. https://trello.com/c/LTYCqnrX/67-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D0%B8-%D0%B0%D0%BF%D1%96-%D0%B5%D0%BD%D0%B4%D0%BF%D0%BE%D0%B9%D0%BD%D1%82%D0%B8-%D0%B4%D0%BB%D1%8F-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D1%96%D1%97
3. https://trello.com/c/lbOJCUrM/68-%D1%80%D0%BE%D0%B7%D1%80%D0%BE%D0%B1%D0%B8%D1%82%D0%B8-%D1%82%D0%B0-%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%B8-%D0%BF%D0%BE%D0%BB%D1%96%D1%82%D0%B8%D0%BA%D1%83-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%96%D0%B2-%D0%B4%D0%BE%D0%B2%D0%B6%D0%B8%D0%BD%D0%B0-%D0%BD%D0%B0%D0%B1%D1%96%D1%80-%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D1%96%D0%B2-%D1%96%D0%BD%D1%96%D1%86%D1%96%D0%B0%D1%86%D1%96%D1%8F-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8E
4. https://trello.com/c/3ffVwvqh/77-%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%B8-%D0%BC%D0%BE%D0%B6%D0%BB%D0%B8%D0%B2%D1%96%D1%81%D1%82%D1%8C-%D0%B2%D1%96%D0%B4%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D0%B8%D1%81%D1%8C-%D0%B2%D1%96%D0%B4-%D1%80%D0%BE%D0%B7%D1%81%D0%B8%D0%BB%D0%BA%D0%B8
5. https://trello.com/c/6ZBVgQWG/78-%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%B8-%D0%BC%D0%BE%D0%B4%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%83-%D0%BC%D0%BE%D0%B6%D0%BB%D0%B8%D0%B2%D1%96%D1%81%D1%82%D1%8C-%D0%B2%D1%96%D0%B4%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D0%BB%D0%B8%D1%81%D1%82%D1%96%D0%B2-%D0%BD%D0%B0%D0%BF%D1%80%D1%8F%D0%BC%D1%83-%D0%BA%D0%BE%D1%80%D0%B8%D1%81%D1%82%D1%83%D0%B2%D0%B0%D1%87%D1%83

Удачі тому, хто буде перевіряти

2019-09-18 18:58 UTC, m-pasha commented
@Martinfree @Azrael-git why you opened this PR? it's similar to PR #31

2019-09-18 19:00 UTC, m-pasha commented on api/authentication/models.py
> +from settings import base
check comment from #31

2019-09-18 19:15 UTC, Martinfree commented
It's not similar, this is request to master branch with all working tasks

2019-09-18 19:41 UTC, pavlo-mk requested changes
added some comments, please let me know if you have some questions

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +        print('save user ::: ',self,args,kwargs)
remove this `print`

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +from settings import base
> use example in [docs](https://docs.djangoproject.com/en/2.2/topics/settings/#using-settings-in-python-code) `from django.conf import settings`

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +    code = models.CharField(max_length=256,blank=True,default="")
add `space` after comma please

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +    def get_verification_code(self,email):
the same, please add space after comma

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +        if code:
the same from #31 
> what will be if no code in args? please update logic for this method
> What happens when this if statement fails?

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +            except SignatureExpired:
from PR #31 
> second `except` not need at this place, please check the logic

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +        if code:
the same questions
What will be if no code in args? please update logic for this method
What happens when this if statement fails?

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +                print(e)
use `raise e` for return error msg, in future we will use all msg for logging

2019-09-18 19:41 UTC, m-pasha commented on api/authentication/models.py
> +                print('exception ::: ',e)
use `raise`

2019-09-22 18:33 UTC, pavlo-mk requested changes
Please add small changes in the code, 
and FYI if you have many small updates in review you can make only one commit for your updates.
Thanks.

2019-09-22 18:33 UTC, m-pasha commented on api/authentication/models.py
> +from settings.base import (
its bad practice, please dont use this import in your code never. Please see in [docs example](https://docs.djangoproject.com/en/2.2/topics/settings/#using-settings-in-python-code) for import settings

2019-09-24 16:36 UTC, pavlo-mk requested changes
Looks good for me. please make small changes.

2019-09-24 16:36 UTC, m-pasha commented on api/authentication/models.py
> +                   'VERIFICATION_URL': VERIFICATION_URL,
unknown var `VERIFICATION_URL`

2019-09-24 16:36 UTC, m-pasha commented on api/authentication/models.py
> +                   'link': datetime.datetime.today() + datetime.timedelta(days=VERIFICATION_CODE_EXPIRED)
unknown  var `VERIFICATION_CODE_EXPIRED`, will get `NameError`

2019-09-24 19:18 UTC, pavlo-mk approved these changes

2019-09-24 19:20 UTC, m-pasha commented
Cc @klekhaav ^^.
Please check if you have a time.

2019-09-24 19:20 UTC, merged