Unit tests #2
sp-team-lutsk/cyber_security_web_portal pull request #33
Opened 2019-09-20 19:08 UTC by Azrael-git

1. Add many tests (more then 99%)
2. Fixed spaces
3. Fixed logic
4. Delete trash code
Trello card: https://trello.com/c/RghxTHTW/62-unit-tests-coverage-for-all-updates

2019-09-22 18:43 UTC, pavlo-mk requested changes
Please make updates and merge #32 and later I think we can approve this PR

2019-09-22 18:43 UTC, m-pasha commented on api/authentication/models.py
> +from settings import base
the same issue this import settings. dont use this import in future

2019-09-24 19:23 UTC, m-pasha commented
@Azrael-git please make pull from `master` into this branch and reassign me for review.

2019-09-25 15:24 UTC, Azrael-git commented
> @Azrael-git please make pull from `master` into this branch and reassign me for review.

Resolved

2019-09-25 16:15 UTC, pavlo-mk approved these changes
LGTM.

2019-09-25 16:20 UTC, merged