Int news
sp-team-lutsk/cyber_security_web_portal pull request #56
Opened 2019-11-09 16:52 UTC by romaoksenyuk

Додати Rest API ендпойнти для int_news
https://trello.com/c/6JTuRbKt/72-%D0%B4%D0%BE%D0%B4%D0%B0%D1%82%D0%B8-rest-api-%D0%B5%D0%BD%D0%B4%D0%BF%D0%BE%D0%B9%D0%BD%D1%82%D0%B8-%D0%B4%D0%BB%D1%8F-intnews

2019-11-09 20:19 UTC, klekhaav commented
please resolve conflicts

2019-11-11 07:28 UTC, pavlo-mk requested changes
Requested changes in this PR. I didnt uptedstand why you added all files in this PR, whats happened in your editor?)🤔

2019-11-11 07:28 UTC, m-pasha commented on api/ext_news/views.py
> +            return Response({'Status':'OK'},status=status.HTTP_200_OK)
You get return method for first item in `for` cycle. Is it correct?

2019-11-11 07:28 UTC, m-pasha commented on api/ext_news/views.py
> +            return None
the same as above. get return method for first item in `for`.

2019-11-11 07:28 UTC, m-pasha commented on api/ext_news/views.py
> +    def Mailing():
please use name for methods with small letters.

2019-11-11 08:17 UTC, merged