Api check
sp-team-lutsk/cyber_security_web_portal pull request #69
Opened 2019-12-07 20:08 UTC by dzhyhalyuk

https://trello.com/c/hSW3YSy3/124-backend-bulk-test-and-optimization

2019-12-09 15:32 UTC, Martinfree commented on api/int_news/views.py
> +
@Green5tar please check why it's not working

2019-12-09 16:33 UTC, Azrael-git requested changes
Please make changes, as i show you in my last commit in this PR. After that I will check again.

Good luck!

2019-12-09 16:33 UTC, Azrael-git commented on api/authentication/serializers.py
> -    faculty = serializers.CharField(max_length=128)
Need to be a FacultySerializer field

2019-12-09 16:33 UTC, Azrael-git commented on api/authentication/serializers.py
> -    faculty = serializers.CharField(max_length=128)
Need to be a FacultySerializer field

2019-12-09 16:33 UTC, Azrael-git commented on api/authentication/serializers.py
> -    profession = serializers.CharField(max_length=128)
Need to be a ProfessionSerializer field

2019-12-10 20:01 UTC, Azrael-git requested changes

2019-12-10 20:01 UTC, Azrael-git commented on api/authentication/serializers.py
> +        print(data)
Delete print

2019-12-10 20:01 UTC, Azrael-git commented on api/authentication/serializers.py
> +            print(f2)
Delete print

2019-12-10 20:01 UTC, Azrael-git commented on api/authentication/views.py
> +                print(request.data)
Delete print

2019-12-12 12:18 UTC, Azrael-git requested changes

2019-12-12 12:18 UTC, Azrael-git commented on api/authentication/views.py
>          number = args[0]
In decorator you're using kwargs, so args cause error. Need to be fixed. You have to use only kwargs variable

2019-12-12 12:18 UTC, Azrael-git commented on api/authentication/views.py
>      def delete(self, request, *args, **kwargs):
In decorator you're using kwargs, so args cause error. Need to be fixed. You have to use only kwargs variable

2019-12-12 12:18 UTC, Azrael-git commented on api/authentication/views.py
> -        number = args[0].get('id')
In decorator you're using kwargs, so args cause error. Need to be fixed. You have to use only kwargs variable

2019-12-12 12:19 UTC, Azrael-git commented
And check all views.py for same mistakes

2019-12-12 12:31 UTC, Azrael-git requested changes

2019-12-12 12:31 UTC, Azrael-git commented on api/authentication/views.py
> +    #@permission("IsStaffUser")
Why have you commented this?

2019-12-12 16:36 UTC, Azrael-git commented
I think good this time

2019-12-12 16:36 UTC, Azrael-git approved these changes

2019-12-12 19:29 UTC, merged